version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wongnok-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass2word
      POSTGRES_DB: wongnok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
